### ISSUE TITLE
Incorrect required version

### ISSUE THREAD

**Issue by jaamo** [WordPress/playground-tools#103]
I tried to run wp-now with Node 16 and got this error message:

`This script is requires node version v18.0.0 or above; found v16.20.2`

I switched to Node 18 and tried to run the command with blueprint:

`wp-now start --blueprint=blueprint.json`

But got an error:

```
Starting the server......
directory: /srv/www/app
mode: plugin
php: 8.0
wp: latest
WordPress latest folder already exists. Skipping download.
SQLite folder already exists. Skipping download.
blueprint steps: 1
ReferenceError: CustomEvent is not definedReferenceError: CustomEvent is not defined
    at F.notifyProgress (file:///home/myuser/.nvm/versions/node/v18.17.1/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:725:11)
    at F.finish (file:///home/myuser/.nvm/versions/node/v18.17.1/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:664:165)
    at Object.run (file:///home/myuser/.nvm/versions/node/v18.17.1/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:2017:11)
    at async yt (file:///home/myuser/.nvm/versions/node/v18.17.1/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:2079:3)
    at async startWPNow (file:///home/myuser/.nvm/versions/node/v18.17.1/lib/node_modules/@wp-now/wp-now/main.js:596:5)
    at async startServer (file:///home/myuser/.nvm/versions/node/v18.17.1/lib/node_modules/@wp-now/wp-now/main.js:865:42)
    at async Object.handler (file:///home/myuser/.nvm/versions/node/v18.17.1/lib/node_modules/@wp-now/wp-now/main.js:1037:25)
Failed to start the server: CustomEvent is not defined
```

After some debugging I found out that CustomEvent is supported from Node 19 onwards:
https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent#browser_compatibility

I switched to Node 20 and the command worked.

Seems that the suggested Node version 18 is incorrect.

I'm using wp-now version 0.1.61.

**Comment by danielbachhuber** [comment]
Thanks for the report, @jaamo !

This is actually a known issue that we were too lazy to address when we added the version check. I'm including some more explicit checks in https://github.com/WordPress/playground-tools/pull/105
