### ISSUE TITLE
Can't start wp-now on Windows OS because of file path fatal

### ISSUE THREAD

**Issue by t-hamano** [WordPress/playground-tools#11]
I have tried wp-now on both Windows host OS and WSL2 and could not start it. Ths may be a problem with my environment, is there anything I should try?

### Commands executed

```
git clone https://github.com/WordPress/twentytwentythree.git
npm install -g @wp-now/wp-now
cd ./twentytwentythree
wp-now start
```

### Occurred Error

```
ReferenceError: Event is not defined
    at Object.<anonymous> (/home/{username}/.volta/tools/image/packages/@wp-now/wp-now/lib/node_modules/@wp-now/wp-now/node_modules/@php-wasm/node/index.cjs:66566:33)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:203:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
    at async handleMainPromise (internal/modules/run_main.js:59:12)
```

### Environment

Note: Both environments use Volta as their version control tool.

#### Windows Host

- OS: Windows OS 11
- Node Version: 14.21.1

### WSL2

- OS: Ubuntu 20.04.4 LTS
- Node Version: Tested with both 14.21.3 and 16.18.0

**Comment by adamziel** [comment]
@t-hamano You'll need Node.js 18+, the error message isn't very clear about that unfortunately – I'd love to clarify it.

**Comment by t-hamano** [comment]
@adamziel 
Thanks for the info!

I was able to move beyond the error in Windows OS by changing the Node version to 18, but another error occurred.

<details><summary>Error Log</summary>

```
wp-now start
Starting the server......
directory: D:\Desktop\twentytwentythree
mode: theme
php: 8.0
wp: latest
Downloading WordPress latest...
Downloading SQLite...
Error: Could not mount C:\Users\tetsuaki.hamano\.wp-now\mu-plugins: There is no such file or directory OR the parent directory does not exist.
    at descriptor.value (C:\Users\tetsuaki.hamano\AppData\Local\Volta\tools\image\packages\@wp-now\wp-now\node_modules\@wp-now\wp-now\node_modules\@php-wasm\node\index.cjs:67333:17)
    at mountMuPlugins (file:///C:/Users/tetsuaki.hamano/AppData/Local/Volta/tools/image/packages/@wp-now/wp-now/node_modules/@wp-now/wp-now/main.js:623:7)
    at runPluginOrThemeMode (file:///C:/Users/tetsuaki.hamano/AppData/Local/Volta/tools/image/packages/@wp-now/wp-now/node_modules/@wp-now/wp-now/main.js:589:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/Users/tetsuaki.hamano/AppData/Local/Volta/tools/image/packages/@wp-now/wp-now/node_modules/@wp-now/wp-now/main.js:501:9
    at async applyToInstances (file:///C:/Users/tetsuaki.hamano/AppData/Local/Volta/tools/image/packages/@wp-now/wp-now/node_modules/@wp-now/wp-now/main.js:437:5)
    at async startWPNow (file:///C:/Users/tetsuaki.hamano/AppData/Local/Volta/tools/image/packages/@wp-now/wp-now/node_modules/@wp-now/wp-now/main.js:486:3)
    at async startServer (file:///C:/Users/tetsuaki.hamano/AppData/Local/Volta/tools/image/packages/@wp-now/wp-now/node_modules/@wp-now/wp-now/main.js:707:42)
    at async Object.handler (file:///C:/Users/tetsuaki.hamano/AppData/Local/Volta/tools/image/packages/@wp-now/wp-now/node_modules/@wp-now/wp-now/main.js:864:25) {
  [cause]: ErrnoError
      at Object.ensureErrnoError (C:\Users\tetsuaki.hamano\AppData\Local\Volta\tools\image\packages\@wp-now\wp-now\node_modules\@wp-now\wp-now\node_modules\@php-wasm\node\index.cjs:20233:33)
      at Object.staticInit (C:\Users\tetsuaki.hamano\AppData\Local\Volta\tools\image\packages\@wp-now\wp-now\node_modules\@wp-now\wp-now\node_modules\@php-wasm\node\index.cjs:20241:10)
      at Object.init3 (C:\Users\tetsuaki.hamano\AppData\Local\Volta\tools\image\packages\@wp-now\wp-now\node_modules\@wp-now\wp-now\node_modules\@php-wasm\node\index.cjs:24083:6)
      at loadPHPRuntime (C:\Users\tetsuaki.hamano\AppData\Local\Volta\tools\image\packages\@wp-now\wp-now\node_modules\@wp-now\wp-now\node_modules\@php-wasm\node\index.cjs:67352:38)
      at doLoad (C:\Users\tetsuaki.hamano\AppData\Local\Volta\tools\image\packages\@wp-now\wp-now\node_modules\@wp-now\wp-now\node_modules\@php-wasm\node\index.cjs:68234:31)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async _NodePHP.load (C:\Users\tetsuaki.hamano\AppData\Local\Volta\tools\image\packages\@wp-now\wp-now\node_modules\@wp-now\wp-now\node_modules\@php-wasm\node\index.cjs:68206:12)
      at async startWPNow (file:///C:/Users/tetsuaki.hamano/AppData/Local/Volta/tools/image/packages/@wp-now/wp-now/node_modules/@wp-now/wp-now/main.js:460:7)
      at async startServer (file:///C:/Users/tetsuaki.hamano/AppData/Local/Volta/tools/image/packages/@wp-now/wp-now/node_modules/@wp-now/wp-now/main.js:707:42)
      at async Object.handler (file:///C:/Users/tetsuaki.hamano/AppData/Local/Volta/tools/image/packages/@wp-now/wp-now/node_modules/@wp-now/wp-now/main.js:864:25) {
    node: undefined,
    setErrno: [Function (anonymous)],
    errno: 44,
    message: 'FS error'
  }
}
```

</details> 

The mount path (`C:\Users\tetsuaki.hamano\.wp-now\mu-plugins`) indicated by this error exists on the host OS. However, compared to the results of the WSL2 run, we noticed that the following directories are missing:

- `C:\Users\tetsuaki.hamano\.wp-now\wp-content\twentytwentythree-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\mu-plugin`
- `C:\Users\tetsuaki.hamano\.wp-now\wp-content\twentytwentythree-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\database`

I still don't understand the project, but if I have time I will try to find the cause.

**Comment by jason3by2** [comment]
Can confirm I'm getting the exact same error, using node v18.16.0, will report back if I can get past it.

**Comment by adamziel** [comment]
Interesting! Thank you so much for surfacing this issue @t-hamano and helping to triage @jason3by2! This helps with making it work for all the Windows users out there.

Solutions-wise, I wonder if this path is even visible/accessible from Node.js. Could it be a permissions issue? Could that be an issue with mixing `file:///C:/` notation and `C:\` notation?

cc @danielbachhuber @sejas @wojtekn

**Comment by t-hamano** [comment]
> Could that be an issue with mixing file:///C:/ notation and C:\ notation?

The URI with the `file:` protocol shown in the error log seems to be at least accessible from the browser. Therefore, I believe this notation is correct:

![file-protcol](https://github.com/WordPress/wordpress-playground/assets/54422211/29ba15e3-2456-476e-a18c-5c636d962bc9)

> at mountMuPlugins (file:///C:/Users/tetsuaki.hamano/AppData/Local/Volta/tools/image/packages/@wp-now/wp-now/node_modules/@wp-now/wp-now/main.js:623:7)

The location indicated by this error is this line:

https://github.com/WordPress/wordpress-playground/blob/043f677f36528e72108d8d6fa8b4d311ec43bf2d/packages/wp-now/src/wp-now.ts#L296

Perhaps `vfsDocumentRoot` is not the correct path?

**Comment by richard-bonk-bf** [comment]
> @adamziel Thanks for the info!
> 
> I was able to move beyond the error in Windows OS by changing the Node version to 18, but another error occurred.
> 
> Error Log
> The mount path (`C:\Users\tetsuaki.hamano\.wp-now\mu-plugins`) indicated by this error exists on the host OS. However, compared to the results of the WSL2 run, we noticed that the following directories are missing:
> 
> * `C:\Users\tetsuaki.hamano\.wp-now\wp-content\twentytwentythree-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\mu-plugin`
> * `C:\Users\tetsuaki.hamano\.wp-now\wp-content\twentytwentythree-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\database`
> 
> I still don't understand the project, but if I have time I will try to find the cause.

I am getting the same error.

**Comment by danielbachhuber** [comment]
@t-hamano @richard-bonk-bf @narinder9 I'm unable to reproduce because I don't have a Windows machine, unfortunately. My _guess_ is that it's a path issue. To start on the debugging journey, can you [install from Git clone](https://github.com/WordPress/wordpress-playground/blob/trunk/packages/wp-now/CONTRIBUTING.md) and see if the issue reproduces with `nx preview wp-now start` ?

**Comment by t-hamano** [comment]
@danielbachhuber

Unfortunately, because that script contains UNIX commands, it cannot be debugged on the Windows host OS. The results of the `nx preview wp-now start` command are shown in the video below:

https://github.com/WordPress/wordpress-playground/assets/54422211/c9ab5f9f-c3d4-4735-9039-fe148cf58a68

If on WSL, that command will work fine, but will instead cause the problems mentioned in [this comment](https://github.com/WordPress/wordpress-playground/issues/435#issuecomment-1561298266). Also, this problem would need to be verified on a Windows host OS, not a WSL.

This is why I submitted WordPress/wordpress-playground#435 😅

**Comment by danielbachhuber** [comment]
@t-hamano I guess this shows how thoroughly we tested on Windows 😅

All of this makes sense, thanks! I guess we'll need to figure out a solution for WordPress/wordpress-playground#435 first.

**Comment by wojtekn** [comment]
I reproduced that issue on Windows 11 with PowerShell:

```
PS C:\Users\wojtek\playground-tools> wp-now start --path=../wordpress-seo
Starting the server......
directory: ../wordpress-seo
mode: plugin
php: 8.0
wp: latest
Downloading WordPress latest...
Downloading SQLite...
Error: Could not mount C:\Users\wojtek\.wp-now\mu-plugins: There is no such file or directory OR the parent directory does not exist.    at descriptor.value (C:\Users\wojtek\AppData\Roaming\npm\node_modules\@wp-now\wp-now\node_modules\@php-wasm\node\index.cjs:67405:17)
[...]
```

Then I tried running the development version of the `wp-now` tool to debug it, but I couldn't run the build on Windows. I reported it under another ticket https://github.com/WordPress/playground-tools/issues/66. We must fix the build issue to debug the mounting problem more.

**Comment by adamziel** [comment]
https://github.com/WordPress/playground-tools/blob/4a0ea12abccca970aaf8e233189351b465f1a153/packages/wp-now/src/wp-now.ts#L321-L326

The first `path.join()` yields `C:\Users\adam\.wp-now\mu-plugins` which is fine

The second `path.join()` yields `\var\www\html\wp-content\mu-plugins` which is not a valid path in the VFS

So – we can’t use path.join for VFS paths because it uses the Windows-style slashes on Windows.

**Comment by t-hamano** [comment]
I reinstalled the latest wp-now including #71 on my Windows host OS. I was able to boot successfully and would like to close this issue.

Thank you so much!

**Comment by danielbachhuber** [comment]
Thanks for your help tracking it down, @t-hamano !

**Comment by jason3by2** [comment]
Heyas, just wanted to pop back in here to confirm that the latest version also runs successfully for me on win10.
Nice work all! :)
