### ISSUE TITLE
Getting Error: Could not mount .../.wp-now/sqlite-database-integration-main/db.copy: Not a directory or a symbolic link to a directory.

### ISSUE THREAD

**Issue by jakubmikita** [WordPress/playground-tools#112]
Full error:

```
kuba@Kuba:/mnt/c/Users/Kuba/www/now$ wp-now start
Starting the server......
directory: /mnt/c/Users/Kuba/www/now
mode: playground
php: 8.0
wp: latest
WordPress latest folder already exists. Skipping download.
SQLite folder already exists. Skipping download.
Error: Could not mount /home/kuba/.wp-now/sqlite-database-integration-main/db.copy: Not a directory or a symbolic link to a directory.
    at descriptor.value (/home/kuba/.nvm/versions/node/v20.8.0/lib/node_modules/@wp-now/wp-now/node_modules/@php-wasm/node/index.cjs:67405:17)
    at mountSqlitePlugin (file:///home/kuba/.nvm/versions/node/v20.8.0/lib/node_modules/@wp-now/wp-now/main.js:767:9)
    at runWpPlaygroundMode (file:///home/kuba/.nvm/versions/node/v20.8.0/lib/node_modules/@wp-now/wp-now/main.js:713:3)
    at async file:///home/kuba/.nvm/versions/node/v20.8.0/lib/node_modules/@wp-now/wp-now/main.js:585:9
    at async applyToInstances (file:///home/kuba/.nvm/versions/node/v20.8.0/lib/node_modules/@wp-now/wp-now/main.js:510:5)
    at async startWPNow (file:///home/kuba/.nvm/versions/node/v20.8.0/lib/node_modules/@wp-now/wp-now/main.js:567:3)
    at async startServer (file:///home/kuba/.nvm/versions/node/v20.8.0/lib/node_modules/@wp-now/wp-now/main.js:865:42)
    at async Object.handler (file:///home/kuba/.nvm/versions/node/v20.8.0/lib/node_modules/@wp-now/wp-now/main.js:1037:25) {
  [cause]: ErrnoError
      at Object.ensureErrnoError (/home/kuba/.nvm/versions/node/v20.8.0/lib/node_modules/@wp-now/wp-now/node_modules/@php-wasm/node/index.cjs:20257:33)
      at Object.staticInit (/home/kuba/.nvm/versions/node/v20.8.0/lib/node_modules/@wp-now/wp-now/node_modules/@php-wasm/node/index.cjs:20265:10)
      at Object.init3 (/home/kuba/.nvm/versions/node/v20.8.0/lib/node_modules/@wp-now/wp-now/node_modules/@php-wasm/node/index.cjs:24107:6)
      at loadPHPRuntime (/home/kuba/.nvm/versions/node/v20.8.0/lib/node_modules/@wp-now/wp-now/node_modules/@php-wasm/node/index.cjs:67424:38)
      at doLoad (/home/kuba/.nvm/versions/node/v20.8.0/lib/node_modules/@wp-now/wp-now/node_modules/@php-wasm/node/index.cjs:68306:31)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async _NodePHP.load (/home/kuba/.nvm/versions/node/v20.8.0/lib/node_modules/@wp-now/wp-now/node_modules/@php-wasm/node/index.cjs:68278:12)
      at async startWPNow (file:///home/kuba/.nvm/versions/node/v20.8.0/lib/node_modules/@wp-now/wp-now/main.js:533:7)
      at async startServer (file:///home/kuba/.nvm/versions/node/v20.8.0/lib/node_modules/@wp-now/wp-now/main.js:865:42)
      at async Object.handler (file:///home/kuba/.nvm/versions/node/v20.8.0/lib/node_modules/@wp-now/wp-now/main.js:1037:25) {
    node: undefined,
    setErrno: [Function (anonymous)],
    errno: 54,
    message: 'FS error'
  }
}
Failed to start the server: Could not mount /home/kuba/.wp-now/sqlite-database-integration-main/db.copy: Not a directory or a symbolic link to a directory.
```

- Running in WSL
- Node v20.8.0
- npm v10.1.0

The file is there, though:

```
kuba@Kuba:~/.wp-now/sqlite-database-integration-main$ ls
LICENSE       admin-notices.php  constants.php  deactivate.php    load.php    wp-includes
activate.php  admin-page.php     db.copy        health-check.php  readme.txt
```

**Comment by danielbachhuber** [comment]
Thanks for the report, @jakubmikita !

> Running in WSL

Oy vey, I have no idea what the issue might be here. Any ideas on your end?

**Comment by jakubmikita** [comment]
Interestingly, on my other PC, it starts up without an issue. I'll reinstall the WSL and start with vanilla Ubuntu.

What makes me think is the error that specifically says "Not a directory or a symbolic link to a directory.", while it's a file. But maybe it's just a generic error.

**Comment by jakubmikita** [comment]
A complete reinstall of WSL helped, yaay!

**Comment by danielbachhuber** [comment]
@jakubmikita Glad to hear you found a solution! Thanks for reporting back 😊
