### ISSUE TITLE
wp-now: ReferenceError: DOMParser is not defined while installing the plugin

### ISSUE THREAD

**Issue by jakubmikita** [WordPress/playground-tools#113]
My blueprint:

```json
{
    "$schema": "https://playground.wordpress.net/blueprint-schema.json",
    "landingPage": "/wp-admin/",
    "preferredVersions": {
        "php": "8.0",
        "wp": "latest"
    },
    "steps": [
        {
            "step": "login",
            "username": "admin",
            "password": "password"
        },
        {
            "step": "installPlugin",
            "pluginZipFile": {
                "resource": "wordpress.org/plugins",
                "slug": "notification"
            },
            "options": {
                "activate": true
            }
        }
    ]
}
```

And the result:
```
kuba@Kuba:/mnt/c/Users/Kuba/www/now$ wp-now start --blueprint=env.json
Starting the server......
directory: /mnt/c/Users/Kuba/www/now
mode: playground
php: 8.0
wp: latest
WordPress latest folder already exists. Skipping download.
SQLite folder already exists. Skipping download.
blueprint steps: 2
Blueprint step completed: login
Proceeding without the Notification theme. Could not install it in wp-admin. The original error was: ReferenceError: DOMParser is not defined
ReferenceError: DOMParser is not defined
    at S (file:///home/kuba/.nvm/versions/node/v20.8.0/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:35:3)
    at Module.xe [as installPlugin] (file:///home/kuba/.nvm/versions/node/v20.8.0/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:351:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async o (file:///home/kuba/.nvm/versions/node/v20.8.0/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:2044:30)
    at async Object.run (file:///home/kuba/.nvm/versions/node/v20.8.0/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:2007:21)
    at async yt (file:///home/kuba/.nvm/versions/node/v20.8.0/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:2079:3)
    at async startWPNow (file:///home/kuba/.nvm/versions/node/v20.8.0/lib/node_modules/@wp-now/wp-now/main.js:596:5)
    at async startServer (file:///home/kuba/.nvm/versions/node/v20.8.0/lib/node_modules/@wp-now/wp-now/main.js:865:42)
    at async Object.handler (file:///home/kuba/.nvm/versions/node/v20.8.0/lib/node_modules/@wp-now/wp-now/main.js:1037:25)
Blueprint step completed: installPlugin
Server running at http://localhost:8881
spawn xdg-open ENOENT
```

The plugin can be installed just fine from the wp-admin.

Also looks like there's a small typo:
> Proceeding without the Notification **theme**

**Comment by adamziel** [comment]
@sejas This is because the `activatePlugin` step used to rely on the DOMParser API. It no longer does thanks to this excellent PR by @eliot-akira: https://github.com/WordPress/wordpress-playground/pull/427. Was that already published to npm in the 0.2.0 release? If so, then numping the `@wp-playground/blueprints` dependency to 0.2.0 will solve this.

**Comment by sejas** [comment]
I've created a draft PR, but it's not so easy. We may need to modify the blueprints to be more isomorphic.

@adamziel, would you have bandwidth this week to help me a bit?

- https://github.com/WordPress/playground-tools/pull/116

**Comment by adamziel** [comment]
@sejas I replied in that PR, thank you for looking into this!

**Comment by sejas** [comment]
After updating the dependencies that add the Polyfills, I'm still seeing an error thrown by `crypto.randomUUID`. I created a PR that fixes it. https://github.com/WordPress/playground-tools/pull/153

**Comment by adamziel** [comment]
@sejas can this issue be closed now?

**Comment by sejas** [comment]
Yes!, Let's close it, the installPlugin and installTheme blueprints are already fixed. 👌
