### ISSUE TITLE
wp-now: EPERM operation not permitted: rename

### ISSUE THREAD

**Issue by Humanify-nl** [WordPress/playground-tools#114]
I am trying to do a testrun of wp-now. When running `wp-now start`, I get the following error:

`Error: EPERM: operation not permitted, rename 'C:\Users\Username\AppData\Local\Temp\wordpress' -> 'C:\Users\Username\.wp-now\wordpress-versions\latest'`

My environment:

- Windows 10
- NVM for windows (set to use node 20.8.0)
- NPM
- Powershell (run as admin)

Full error stack:
```
Error: EPERM: operation not permitted, rename 'C:\Users\Humanify\AppData\Local\Temp\wordpress' -> 'C:\Users\Humanify\.wp-now\wordpress-versions\latest'
    at Object.renameSync (node:fs:1023:3)
    at rename (C:\Users\Humanify\AppData\Roaming\nvm\v20.8.0\node_modules\@wp-now\wp-now\node_modules\fs-extra\lib\move\move-sync.js:38:8)
    at doRename (C:\Users\Humanify\AppData\Roaming\nvm\v20.8.0\node_modules\@wp-now\wp-now\node_modules\fs-extra\lib\move\move-sync.js:30:12)
    at Object.moveSync (C:\Users\Humanify\AppData\Roaming\nvm\v20.8.0\node_modules\@wp-now\wp-now\node_modules\fs-extra\lib\move\move-sync.js:17:10)
    at downloadWordPress (file:///C:/Users/Humanify/AppData/Roaming/nvm/v20.8.0/node_modules/@wp-now/wp-now/main.js:339:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async startWPNow (file:///C:/Users/Humanify/AppData/Roaming/nvm/v20.8.0/node_modules/@wp-now/wp-now/main.js:555:3)
    at async startServer (file:///C:/Users/Humanify/AppData/Roaming/nvm/v20.8.0/node_modules/@wp-now/wp-now/main.js:865:42)
    at async Object.handler (file:///C:/Users/Humanify/AppData/Roaming/nvm/v20.8.0/node_modules/@wp-now/wp-now/main.js:1037:25) {
  errno: -4048,
  syscall: 'rename',
  code: 'EPERM',
  path: 'C:\\Users\\Username\\AppData\\Local\\Temp\\wordpress',
  dest: 'C:\\Users\\Username\\.wp-now\\wordpress-versions\\latest'
}
```

**Comment by shinhwas** [comment]
+1 

- windows 11
- NVM for windows (set to use node 20.10.0)

**Comment by Tropicalista** [comment]
Same error here.

running `npm cache clean --force` solved my problem.

Also close VS code can be helpful.
