### ISSUE TITLE
wp-now: server stop working when trying to access wp-admin 

### ISSUE THREAD

**Issue by kpotia** [WordPress/playground-tools#118]
When trying to access  wp-admin and wp-login.php I face this error.

```log
/usr/lib/node_modules/@wp-now/wp-now/node_modules/@php-wasm/node/index.cjs:68118
    target.end();
           ^

TypeError: Cannot read properties of undefined (reading 'end')
    at WebSocket3.<anonymous> (/usr/lib/node_modules/@wp-now/wp-now/node_modules/@php-wasm/node/index.cjs:68118:12)
    at WebSocket3.emit (node:events:529:35)
    at WebSocket3.emitClose (/usr/lib/node_modules/@wp-now/wp-now/node_modules/@php-wasm/node/index.cjs:2335:14)
    at Socket.socketOnClose (/usr/lib/node_modules/@wp-now/wp-now/node_modules/@php-wasm/node/index.cjs:2958:19)
    at Socket.emit (node:events:517:28)
    at TCP.<anonymous> (node:net:350:12)

Node.js v18.18.2
```

**Comment by danielbachhuber** [comment]
Interesting! Thanks for the report, @kpotia 

I'm not able to reproduce with Node v18.18.2 and @wp-now/wp-now@0.1.63

Can you share more details about the WordPress install? Does the problem reproduce when you try `wp-now start` in a new empty directory?

**Comment by kpotia** [comment]
I have tried in an empty repository and I am facing the same bug. maybe I need to do some additional configuration to my nodejs.
