### ISSUE TITLE
wp-now: php command doesn't work for relative path

### ISSUE THREAD

**Issue by wojtekn** [WordPress/playground-tools#16]
When I use wp-now in development mode, symlinked using `npm link`, and I try executing PHP script in the current directory, I get an error:

```
$ wp-now php test.php 
[...nx build output here...]
Error: Could not open input file: /Volumes/Sites/wordpress-playground/test.php
    at executePHPFile (file:///Volumes/Sites/wordpress-playground/dist/packages/wp-now/main.js:797:11)
    at async Object.handler (file:///Volumes/Sites/wordpress-playground/dist/packages/wp-now/main.js:895:9)
```

When I use an absolute path, it works:

```
$ wp-now php /Volumes/Sites/vip-directory/test.php
[...nx build output here...]
Hello World!
```

When I install it using npm, it works in both cases:

```
$ wp-now php test.php                                     
Hello World!
```

**Done is**
- I can use relative path parameter in both development and compiled modes

**Comment by adamziel** [comment]
good catch!
