### ISSUE TITLE
'FS error' - Could not mount the DB,

### ISSUE THREAD

**Issue by Zagaz** [WordPress/playground-tools#184]
I'm using wp-now for about 2 weeks, and I'm loving it. 
I'm using WSL (Ubuntu). 

Today I got this crash:

 Starting the server......
directory: /home/abc/sandbox/wp-content/plugins/team-members-block
mode: plugin
php: 8.0
wp: latest
WordPress latest folder already exists. Skipping download.
SQLite folder already exists. Skipping download.
Error: Could not mount /home/abc/.wp-now/sqlite-database-integration-main/db.copy: There is no such file or directory OR the parent directory does not exist.
    at descriptor.value (/home/abc/.nvm/versions/node/v20.9.0/lib/node_modules/@wp-now/wp-now/node_modules/@php-wasm/node/index.cjs:68800:17)
    at mountSqlitePlugin (file:///home/abc/.nvm/versions/node/v20.9.0/lib/node_modules/@wp-now/wp-now/main.js:768:9)
    at runPluginOrThemeMode (file:///home/abc/.nvm/versions/node/v20.9.0/lib/node_modules/@wp-now/wp-now/main.js:698:3)
    at async file:///home/zagaz/.nvm/versions/node/v20.9.0/lib/node_modules/@wp-now/wp-now/main.js:580:9
    at async applyToInstances (file:///home/abc/.nvm/versions/node/v20.9.0/lib/node_modules/@wp-now/wp-now/main.js:520:5)
    at async startWPNow (file:///home/abc/.nvm/versions/node/v20.9.0/lib/node_modules/@wp-now/wp-now/main.js:568:3)
    at async startServer (file:///home/abc/.nvm/versions/node/v20.9.0/lib/node_modules/@wp-now/wp-now/main.js:866:42)
    at async Object.handler (file:///home/abc/.nvm/versions/node/v20.9.0/lib/node_modules/@wp-now/wp-now/main.js:1058:25) {
  [cause]: Error
      at Object.ensureErrnoError (/home/abc/.nvm/versions/node/v20.9.0/lib/node_modules/@wp-now/wp-now/node_modules/@php-wasm/node/index.cjs:27717:33)
      at Object.staticInit (/home/abc/.nvm/versions/node/v20.9.0/lib/node_modules/@wp-now/wp-now/node_modules/@php-wasm/node/index.cjs:27725:10)
      at Object.init4 (/home/abc/.nvm/versions/node/v20.9.0/lib/node_modules/@wp-now/wp-now/node_modules/@php-wasm/node/index.cjs:31666:6)
      at loadPHPRuntime (/home/abc/.nvm/versions/node/v20.9.0/lib/node_modules/@wp-now/wp-now/node_modules/@php-wasm/node/index.cjs:68816:38)
      at doLoad (/home/abc/.nvm/versions/node/v20.9.0/lib/node_modules/@wp-now/wp-now/node_modules/@php-wasm/node/index.cjs:69879:31)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async _NodePHP.load (/home/abc/.nvm/versions/node/v20.9.0/lib/node_modules/@wp-now/wp-now/node_modules/@php-wasm/node/index.cjs:69846:12)
      at async startWPNow (file:///home/abc/.nvm/versions/node/v20.9.0/lib/node_modules/@wp-now/wp-now/main.js:534:7)
      at async startServer (file:///home/abc/.nvm/versions/node/v20.9.0/lib/node_modules/@wp-now/wp-now/main.js:866:42)
      at async Object.handler (file:///home//.nvm/versions/node/v20.9.0/lib/node_modules/@wp-now/wp-now/main.js:1058:25) {
    node: undefined,
    setErrno: [Function (anonymous)],
    errno: 44,
    message: 'FS error'
  }
}
Failed to start the server: Could not mount /home/abc/.wp-now/sqlite-database-integration-main/db.copy: There is no such file or directory OR the parent directory does not exist.

**Comment by adamziel** [comment]
cc @bgrgicak I think this is was fixed in one of your recent PRs, is that so? Let's release a new version on `wp-now` to ship the fix to everyone.

**Comment by bgrgicak** [comment]
Correct, in the next version on wp-now a server restart should fix this.

**Comment by bgrgicak** [comment]
[0.1.65 is now released](https://www.npmjs.com/package/@wp-now/wp-now?activeTab=readme). Updating the package and restarting the server should fix the issue.
