### ISSUE TITLE
wp-now: blueprint with installPlugin steps fails on subsequent runs

### ISSUE THREAD

**Issue by squelchdesign** [WordPress/playground-tools#209]
Possibly related to #178?

I'm developing a plugin which will integrate with the font-awesome plugin, so I have a `blueprint.json` which installs the font-awesome plugin automatically. On the first run it installs perfectly. On a subsequent run, without doing a `--reset`, it tries to install the plugin again and then dies with an error:

```
Error: Error when executing the blueprint step #1 ({"step":"installPlugin","pluginZipFile":{"resource":"wordpress.org/plugins","slug":"font-awesome"},"options":{"activate":true}}) : Could not move /var/www/html/wp-content/tXW4-8lh6nrAqCPMULyn1dppMr^E,v>Nm!i]/assets/Font awesome/font-awesome to /var/www/html/wp-content/plugins/font-awesome: Directory not empty.
    at Object.run (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:9215:37)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runBlueprintSteps (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:9320:3)
    ... 2 lines matching cause stack trace ...
    at async Object.handler (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/main.js:1152:25) {
  [cause]: Error: Could not move /var/www/html/wp-content/tXW4-8lh6nrAqCPMULyn1dppMr^E,v>Nm!i]/assets/Font awesome/font-awesome to /var/www/html/wp-content/plugins/font-awesome: Directory not empty.
      at _NodePHP.mv (/opt/homebrew/lib/node_modules/@wp-now/wp-now/node_modules/@php-wasm/node/index.cjs:73245:13)
      at installAsset (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:1144:20)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.installPlugin (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:1161:34)
      at async o (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:9285:30)
      at async Object.run (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:9212:23)
      at async runBlueprintSteps (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:9320:3)
      at async startWPNow (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/main.js:652:5)
      at async startServer (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/main.js:970:42)
      at async Object.handler (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/main.js:1152:25) {
    [cause]: [<generic error, no stack>] {
      name: 'ErrnoError',
      node: undefined,
      setErrno: [Function (anonymous)],
      errno: 55,
      message: 'FS error'
    }
  }
}
Failed to start the server: Error when executing the blueprint step #1 ({"step":"installPlugin","pluginZipFile":{"resource":"wordpress.org/plugins","slug":"font-awesome"},"options":{"activate":true}}) : Could not move /var/www/html/wp-content/tXW4-8lh6nrAqCPMULyn1dppMr^E,v>Nm!i]/assets/Font awesome/font-awesome to /var/www/html/wp-content/plugins/font-awesome: Directory not empty.
```

I can't see a way of saying "install this plugin, unless it's already there". Obviously I can work around this by always executing wp-now with the `--reset` option, but it'd be useful to be able to retain the state of the installation between runs.

wp-now is my new favourite tool though!

**Comment by bgrgicak** [comment]
This could be related to https://github.com/WordPress/wordpress-playground/issues/1157
@adamziel suggested a workaround in that issue https://github.com/WordPress/wordpress-playground/issues/1157#issuecomment-2027440383

**Comment by squelchdesign** [comment]
> This could be related to https://github.com/WordPress/wordpress-playground/issues/1157

Yes, it looks like a different expression of the same issue.

> @adamziel suggested a workaround in that issue https://github.com/WordPress/wordpress-playground/issues/1157#issuecomment-2027440383

The problem is the workaround fails on the _initial_ run of wp-now…

```
Error: Error when executing the blueprint step #1 ({"step":"rmdir","path":"/var/www/html/wp-content/plugins/font-awesome"}) : Could not remove directory "/var/www/html/wp-content/plugins/font-awesome": There is no such file or directory OR the parent directory does not exist.
    at Object.run (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:9215:37)
    at async runBlueprintSteps (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:9320:3)
    ... 2 lines matching cause stack trace ...
    at async Object.handler (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/main.js:1152:25) {
  [cause]: Error: Could not remove directory "/var/www/html/wp-content/plugins/font-awesome": There is no such file or directory OR the parent directory does not exist.
      at descriptor.value (/opt/homebrew/lib/node_modules/@wp-now/wp-now/node_modules/@php-wasm/node/index.cjs:72642:17)
      at Object.rmdir (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:902:11)
      at o (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:9285:61)
      at async Object.run (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:9212:23)
      at async runBlueprintSteps (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:9320:3)
      at async startWPNow (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/main.js:652:5)
      at async startServer (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/main.js:970:42)
      at async Object.handler (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/main.js:1152:25) {
    [cause]: [<generic error, no stack>] {
      name: 'ErrnoError',
      node: undefined,
      setErrno: [Function (anonymous)],
      errno: 44,
      message: 'FS error'
    }
  }
}
Failed to start the server: Error when executing the blueprint step #1 ({"step":"rmdir","path":"/var/www/html/wp-content/plugins/font-awesome"}) : Could not remove directory "/var/www/html/wp-content/plugins/font-awesome": There is no such file or directory OR the parent directory does not exist.
```

For now the only workaround seems to be to use `--reset`.

**Comment by adamziel** [comment]
Thank you for reporting @squelchdesign! I just added this to [the project board](https://github.com/orgs/WordPress/projects/180).
