### ISSUE TITLE
Sandbox plugin: Uncaught Exception: Could not unzip file in /internal/eval.php:14

### ISSUE THREAD

**Issue by bph** [WordPress/playground-tools#318]
I wanted to test the [Sandbox plugin](https://wordpress.org/plugins/playground/) with my small technical blog and I didn't get far. 

It's hosted on Server Info:
- Linux 5.4.0-169-generic x86_64
- nginx/1.18.0
- PHP: 8.2.13

WordPress 6.6 beta 3

## Error display in modal 
<img width="431" alt="Screenshot 2024-06-22 at 11 15 24" src="https://github.com/WordPress/playground-tools/assets/39980/6c352157-1079-41e4-af0a-621c9bd552d9">

<img width="379" alt="Screenshot 2024-06-22 at 11 15 30" src="https://github.com/WordPress/playground-tools/assets/39980/bd2a7d36-3f65-455a-a847-dbca031b7309">

#Browser Console Errors
Error: PHP.run() failed with exit code 255 and the following output: PHP Fatal error:  Uncaught Exception: Could not unzip file in /internal/eval.php:14
Stack trace:
#0 /internal/eval.php(17): unzip('/tmp/file.zip', '/wordpress')
#1 {main}
  thrown in /internal/eval.php on line 14

    at PHP.run (worker-thread-b7f2a560.js?wpVersion=6.6-beta3&phpVersion=8.2&php-extension=iconv&php-extension=mbstring&php-extension=xml-bundle&php-extension=gd&networking=yes&storage=&site-slug=wordpress:53:1748)
    at async PlaygroundWorkerEndpoint.run (worker-thread-b7f2a560.js?wpVersion=6.6-beta3&phpVersion=8.2&php-extension=iconv&php-extension=mbstring&php-extension=xml-bundle&php-extension=gd&networking=yes&storage=&site-slug=wordpress:4:8867)

---
index.js:222 PHP.run() failed with exit code 255 and the following output: PHP Fatal error:  Uncaught Exception: Could not unzip file in /internal/eval.php:14
Stack trace:
#0 /internal/eval.php(17): unzip('/tmp/file.zip', '/wordpress')
#1 {main}
  thrown in /internal/eval.php on line 14
 Error: PHP.run() failed with exit code 255 and the following output: PHP Fatal error:  Uncaught Exception: Could not unzip file in /internal/eval.php:14
Stack trace:
#0 /internal/eval.php(17): unzip('/tmp/file.zip', '/wordpress')
#1 {main}
  thrown in /internal/eval.php on line 14

    at PHP.run (https://playground.wordpress.net/worker-thread-b7f2a560.js?wpVersion=6.6-be…undle&php-extension=gd&networking=yes&storage=&site-slug=wordpress:53:1748)
    at async PlaygroundWorkerEndpoint.run (https://playground.wordpress.net/worker-thread-b7f2a560.js?wpVersion=6.6-be…bundle&php-extension=gd&networking=yes&storage=&site-slug=wordpress:4:8867)

**Comment by bgrgicak** [comment]
This looks like the zip wasn't correctly generated. @adamziel we should schedule some time to improve this plugin, it seems to break in a lot of scenarios and doesn't scale well.
