### ISSUE TITLE
Cannot start wp-now in dev container: Cannot find module

### ISSUE THREAD

**Issue by KeesCBakker** [WordPress/playground-tools#6]
I'm trying to setup a dev container in VSCode with wp-now. It installs correctly, but when executing the `wp-now start` I get the following message:

> vscode ➜ /workspaces/ktt-wp-post-lists $ wp-now --version
> node:internal/modules/cjs/loader:1075
>   const err = new Error(message);
>               ^
> 
> Error: Cannot find module '/workspaces/ktt-wp-post-lists/package.json'
> Require stack:
> \- /usr/local/share/nvm/versions/node/v18.16.0/lib/node_modules/wp-now/index.js
>     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
>     at Module._load (node:internal/modules/cjs/loader:920:27)
>     at Module.require (node:internal/modules/cjs/loader:1141:19)
>     at require (node:internal/modules/cjs/helpers:110:18)
>     at /usr/local/share/nvm/versions/node/v18.16.0/lib/node_modules/wp-now/index.js:4:19
>     at Object.<anonymous> (/usr/local/share/nvm/versions/node/v18.16.0/lib/node_modules/wp-now/index.js:345:3)
>     at Module._compile (node:internal/modules/cjs/loader:1254:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
>     at Module.load (node:internal/modules/cjs/loader:1117:32)
>     at Module._load (node:internal/modules/cjs/loader:958:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/usr/local/share/nvm/versions/node/v18.16.0/lib/node_modules/wp-now/index.js'
>   ]
> }
> 
> Node.js v18.16.0

This is the code for the `.devcontainer`:

```
// For format details, see https://aka.ms/devcontainer.json. For config options, see the
// README at: https://github.com/devcontainers/templates/tree/main/src/php
{
	"name": "PHP",
	// Or use a Dockerfile or Docker Compose file. More info: https://containers.dev/guide/dockerfile
	"image": "mcr.microsoft.com/devcontainers/php:0-8.2",
	// Features to add to the dev container. More info: https://containers.dev/features.
	// "features": {},
	// Configure tool-specific properties.
	// "customizations": {},
	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	"forwardPorts": [
		8080
	],
	"features": {
		"ghcr.io/devcontainers/features/node:1": {
			"nodeGypDependencies": true,
			"version": "18"
		}
	},
	// Use 'postCreateCommand' to run commands after the container is created.
	"postCreateCommand": "npm install -g wp-now"
	// Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
	// "remoteUser": "root"
}
```

Looks like it installs correctly:

> Running the postCreateCommand from devcontainer.json...
> 
> [31432 ms] Start: Run in container: /bin/sh -c npm install -g wp-now
> 
> added 1 package in 1s
> npm notice
> npm notice New minor version of npm available! 9.5.1 -> 9.6.7
> npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.6.7
> npm notice Run npm install -g npm@9.6.7 to update!
> npm notice
> Done. Press any key to close the terminal.

It is also found on disk:

> vscode ➜ /workspaces/ktt-wp-post-lists (main) $ which wp-now
> /usr/local/share/nvm/versions/node/v18.16.0/bin/wp-now

Any tips on how to proceed?

**Comment by KeesCBakker** [comment]
Looks like I need to install `npm install -g @wp-now/wp-now` instead of `npm install -g wp-now`. Let's try that...

**Comment by KeesCBakker** [comment]
Okay, and we need to install `xdg-utils` in the container.

```
// For format details, see https://aka.ms/devcontainer.json. For config options, see the
// README at: https://github.com/devcontainers/templates/tree/main/src/php
{
	"name": "PHP",
	// Or use a Dockerfile or Docker Compose file. More info: https://containers.dev/guide/dockerfile
	"image": "mcr.microsoft.com/devcontainers/php:0-8.2",
	// Features to add to the dev container. More info: https://containers.dev/features.
	// "features": {},
	// Configure tool-specific properties.
	// "customizations": {},
	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	"forwardPorts": [
		8881
	],
	"features": {
		"ghcr.io/devcontainers/features/node:1": {
			"nodeGypDependencies": true,
			"version": "18"
		},
		"ghcr.io/devcontainers-contrib/features/apt-get-packages:1": {
			"packages": "xdg-utils"
		}
	},
	// Use 'postCreateCommand' to run commands after the container is created.
	"postCreateCommand": "npm install -g @wp-now/wp-now"
	// Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
	// "remoteUser": "root"
}
```

**Comment by adamziel** [comment]
Thank you for reporting @KeesCBakker! Let’s make sure this is documented, or even remove the extra dependency @danielbachhuber @katinthehatsite

**Comment by KeesCBakker** [comment]
Looks like I was installing this package: https://www.npmjs.com/package/wp-now, which is not remotely the right project ;-) but the name collision is something to lookout for. Maybe we can ask the dev to hand over the NPM repo?

I see that my `.wp-now` is not persisted upon rebuilds, so you might want to mount it in your dir:

```
{
	"name": "PHP",
	"dockerFile": "Dockerfile",
	"forwardPorts": [
		8881
	],
	"mounts": [
		"source=${localWorkspaceFolder}/.wp-now,target=/home/vscode/.wp-now,type=bind,consistency=cached"
	]
}
```

And this Dockerfile will speed startup of the container greatly as the installs are in a cached layer:

```
# Start with the same base image
FROM mcr.microsoft.com/devcontainers/php:0-8.2

# Install xdg-utils, curl and gnupg2
RUN apt-get update && apt-get install -y xdg-utils curl gnupg2

# Add the NodeSource distribution
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash -

# Update packages list, install xdg-utils, node.js, npm and clean up cache in the same command
RUN apt-get update && \
    apt-get install -y nodejs && \
    rm -rf /var/lib/apt/lists/*

# Install the npm packages globally
RUN npm install -g npm \
    && npm install -g \
    @wp-now/wp-now \
    node-gyp

```

**Comment by KeesCBakker** [comment]
@adamziel, I had to install the same `xdg-utils` package on my WSL2 env when I was testing this. Decided to switch to dev containers instead.
